policies:
  - name: account-check-config-services
    comment: this service will check all the config services
    resource: account
    region: us-east-1
    filters:
      - type: check-config
        all-resources: true
        global-resources: true
        running: true
